In [2]:
import pandas as pd
import numpy as np

In [3]:
#sufixo="_ativos_mes_anterior"
sufixo=""

In [4]:
# IDENTIFICAÇÃO SE TELHANORTE OU TUMELERO
ID_UNN=1 # 1=TELHANORTE    4=TUMELERO
if ID_UNN == 1:
    empresa='TELHANORTE'
elif ID_UNN == 4:
    empresa = 'TUMELERO'
else: 
    print('ID_UNN deve ser 1=TELHANORTE    4=TUMELERO ')
    print('Abortando notebook!!!!')
    class StopExecution(Exception):
        def _render_traceback_(self):
            pass

    raise StopExecution

print('Apuração da Premiação Coletiva para '+empresa)

Apuração da Premiação Coletiva para TELHANORTE

In [5]:

# Dia da apuração
hoje = pd.to_datetime('today').date()
#hoje = pd.to_datetime('27/04/2022', format="%d/%m/%Y").date()
ANO=str(hoje.year)

In [6]:
# MÍNIMO NPS CONSIDERADO PARA ELEGIBILIDADE DA LOJA AO PRÊMIO COLETIVO TINA
NPS_ALVO=65

In [7]:
# Dias a serem considerados

MES_COMERCIAL=30 # MES COMERCIAL TEM 30 DIAS
MEIO_MES=int(MES_COMERCIAL/2.)

In [8]:
MESES= ['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez']
I_MESES= ['01','02','03','04','05','06','07','08','09','10','11','12']
MES=MESES[hoje.month-1]
I_MES=I_MESES[MESES.index(MES)]
I_MES_ANTERIOR=I_MESES[MESES.index(MES)-1]

In [9]:
MES_ANTERIOR=MESES[MESES.index(MES)-1]
MES_ANTERIOR

'abr'

In [10]:
print('Como a apuração está sendo feita em '+MES+', a apuração coletiva será correspondente ao do mês anterior '+MES_ANTERIOR)

Como a apuração está sendo feita em mai, a apuração coletiva será correspondente ao do mês anterior abr

In [11]:
I_DIAS=pd.to_datetime(ANO+'-'+I_MES_ANTERIOR).days_in_month

In [12]:
print(str(I_DIAS)+' dias em '+MES_ANTERIOR)

30 dias em abr

In [13]:
# Período de Apuração   -   Faltas injustificadas no período
# Fevereiro de 2022
DATA_I = pd.to_datetime(ANO+'-'+I_MES_ANTERIOR+'-01', format='%Y/%m/%d')  # data inicial AAAA-MM-DD
DATA_F = pd.to_datetime(ANO+'-'+I_MES_ANTERIOR+'-'+str(I_DIAS), format='%Y/%m/%d')  # data final AAAA-MM-DD
print('Considerando ')
print('Data de início:')
print(DATA_I)
print('')
print('Data final:')
print(DATA_F)

Considerando
Data de início:
2022-04-01 00:00:00

Data final:
2022-04-30 00:00:00

In [14]:
# Diretório ou pasta base
DIRETORIO='C:/apuracao/'+empresa+'/'
print('Dentro da pasta '+DIRETORIO+' tem a pasta ano e mês? Se não crie como explicado a seguir.')

Dentro da pasta C:/apuracao/TELHANORTE/ tem a pasta ano e mês? Se não crie como explicado a seguir.

In [15]:
print('A apuração da premiação coletiva é correspondente ao mês anterior.')
print('Portanto, buscar arquivos do mês anterior na pasta:')
DIRETORIO_ANTERIOR=DIRETORIO+ANO+'/'+MES_ANTERIOR+'/'
print(DIRETORIO_ANTERIOR)

A apuração da premiação coletiva é correspondente ao mês anterior.
Portanto, buscar arquivos do mês anterior na pasta:
C:/apuracao/TELHANORTE/2022/abr/

In [16]:
DIRETORIO_INFO='C:/apuracao/info/'
print('Pasta com informações bases: '+DIRETORIO_INFO)
print('Aqui deve ter os arquivos com:')

Pasta com informações bases: C:/apuracao/info/
Aqui deve ter os arquivos com:

In [17]:
# ARQUIVO DE ENTRADA: VALORES DE PREMIAÇÃO POR GRUPO DE CARGOS
F_PREMIO_CARGO=DIRETORIO_INFO+'premiacao_cargo_alvo.csv'
print(F_PREMIO_CARGO)

C:/apuracao/info/premiacao_cargo_alvo.csv

In [18]:
# ARQUIVO DE ENTRADA: CARGOS CONTEMPLADO PELA PREMIAÇÃO COLETIVA TINA
F_CARGOS=DIRETORIO_INFO+'cargos_contemplados_grupo.csv'
print(F_CARGOS)

C:/apuracao/info/cargos_contemplados_grupo.csv

In [19]:
# ARQUIVO DE ENTRADA: LOJAS TINA ROLL-OUT DE JANEIRO DE 2022 COM COD_LOJA, SIGLA E NOME
FILE_LOJAS_TINA=DIRETORIO_INFO+'lojas_pilotos_rollout.csv'
print(FILE_LOJAS_TINA)

C:/apuracao/info/lojas_pilotos_rollout.csv

In [20]:
# ARQUIVO DE ENTRADA: ALVOS COLETIVOS DAS LOJAS
F_ALVOS=DIRETORIO_INFO+'target_store.csv'
print('Arquivo de alvos coletivos')
print(F_ALVOS)

Arquivo de alvos coletivos
C:/apuracao/info/target_store.csv

In [21]:
# PASTA COM ARQUIVOS BASES DO RH
DIRETORIO_ENTRA=DIRETORIO+ANO+'/'+MES+'/ORIGINAIS/'
print('Pasta:')
print(DIRETORIO_ENTRA)
print('Coloque nesta pasta os arquivos bases vindos do RH no mês da apuração:')
print('     base de ativos, ')
print('     base de falta injustificada; e')
print('     base de afastamentos.')

Pasta:
C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/
Coloque nesta pasta os arquivos bases vindos do RH no mês da apuração:
     base de ativos,
     base de falta injustificada; e
     base de afastamentos.

In [22]:
# PASTA COM PLANILHA DE CHECAGEM PARA O ANALISTA DE NEGÓCIOS
DIRETORIO_CHECAGEM=DIRETORIO+ANO+'/'+MES+'/CHECAGEM/'
print('A planilha de checagem da apuração coletiva realizada em '+MES+' está aqui:')
print(DIRETORIO_CHECAGEM)

A planilha de checagem da apuração coletiva realizada em mai está aqui:
C:/apuracao/TELHANORTE/2022/mai/CHECAGEM/

In [23]:
# PASTA COM BASES DE VENDAS PUXADAS DO MicroStrategy
DIRETORIO_VENDAS_NPS=DIRETORIO_ENTRA # pasta com vendas do MicroStrategy
print('Pasta:')
print(DIRETORIO_VENDAS_NPS)
print('Coloque nesta pasta a base de VENDAS de '+MES_ANTERIOR+' puxadas no MicroStrategy.')

Pasta:
C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/
Coloque nesta pasta a base de VENDAS de abr puxadas no MicroStrategy.

In [24]:
# PASTA COM BASES DE NPS 
print('Pasta:')
print(DIRETORIO_VENDAS_NPS)
print('Coloque nesta pasta a base de NPS de '+MES_ANTERIOR+' baixada do SOLUX.')

Pasta:
C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/
Coloque nesta pasta a base de NPS de abr baixada do SOLUX.

In [25]:
# PASTA DE SAÍDA DAS VERBAS DE PREMIAÇÕES TINA EM EXCEL A SEREM ENVIADOS AO RH
DIRETORIO_SAI=DIRETORIO+ANO+'/'+MES+'/para_RH/'

In [26]:
# ARQUIVO DE SAÍDA PARA O RH - EM EXCEL
FILE_SAI=DIRETORIO_SAI + "VERBA_4117_PREMIACAO_COLETIVA"+sufixo+".xlsx"
FILE_SAI_SEM=DIRETORIO_SAI + "VERBA_4117_PREMIACAO_COLETIVA_sem_considerar_falta_injustificada"+sufixo+".xlsx"
print('Arquivos de saída para RH')
print(FILE_SAI)

Arquivos de saída para RH
C:/apuracao/TELHANORTE/2022/mai/para_RH/VERBA_4117_PREMIACAO_COLETIVA.xlsx

In [27]:
print('Arquivos de backup SEM CONSIDERAR FALTA INJUSTIFICADA')
print(FILE_SAI_SEM)

Arquivos de backup SEM CONSIDERAR FALTA INJUSTIFICADA
C:/apuracao/TELHANORTE/2022/mai/para_RH/VERBA_4117_PREMIACAO_COLETIVA_sem_considerar_falta_injustificada.xlsx

In [28]:
# ARQUIO DE SAÍDA PARA CHECAGEM DO ANALISTA DE NEGÓCIOS - EM EXCEL
FILE_CHECAGEM=DIRETORIO_CHECAGEM + "CHECANDO_APURACAO_COLETIVA"+sufixo+".xlsx"
print('Planilha para checar a situação dos colaboradores em relação à Premiação Coletiva Tina')
print(FILE_CHECAGEM)

Planilha para checar a situação dos colaboradores em relação à Premiação Coletiva Tina
C:/apuracao/TELHANORTE/2022/mai/CHECAGEM/CHECANDO_APURACAO_COLETIVA.xlsx

In [29]:
# ARQUIO DE SAÍDA PARA CHECAGEM DO ANALISTA DE NEGÓCIOS - EM EXCEL
FILE_CHECAGEM_LOJAS=DIRETORIO_CHECAGEM + "CHECANDO_LOJAS_APURACAO_COLETIVA"+sufixo+".xlsx"
print('Planilha para checar lojas elegíveis à Premiação Coletiva Tina')
print(FILE_CHECAGEM_LOJAS)

Planilha para checar lojas elegíveis à Premiação Coletiva Tina
C:/apuracao/TELHANORTE/2022/mai/CHECAGEM/CHECANDO_LOJAS_APURACAO_COLETIVA.xlsx

In [30]:
# ARQUIO DE SAÍDA PARA CHECAGEM DO ANALISTA DE NEGÓCIOS - EM EXCEL
FILE_CHECAGEM_AFASTADOS=DIRETORIO_CHECAGEM + "CHECANDO_AFASTADOS_APURACAO_COLETIVA"+sufixo+".xlsx"
print('Planilha para checar base de afastados')
print(FILE_CHECAGEM_AFASTADOS)

Planilha para checar base de afastados
C:/apuracao/TELHANORTE/2022/mai/CHECAGEM/CHECANDO_AFASTADOS_APURACAO_COLETIVA.xlsx

In [31]:
# ARQUIVO DE ENTRADA: faltas injustificadas do mês e do mês anterior
F_FALTAS = DIRETORIO_ENTRA+"PREMIACOES TINA.xlsx"
F_FALTAS_MES_ANTERIOR=DIRETORIO_ANTERIOR+"ORIGINAIS/PREMIACOES TINA.xlsx"
print(F_FALTAS_MES_ANTERIOR)
print(F_FALTAS)

C:/apuracao/TELHANORTE/2022/abr/ORIGINAIS/PREMIACOES TINA.xlsx
C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/PREMIACOES TINA.xlsx

In [32]:
import os
# ARQUIVO DE ENTRADA: base de afastados do mês anterior
for file in os.listdir(DIRETORIO_ENTRA):
    if file.startswith('Empregados-Afastados-19000101-a-') & file.endswith('.xlsx'):
        F_AFASTADOS=os.path.join(DIRETORIO_ENTRA, file)
F_AFASTADOS # BASE DE AFASTAMENTOS DESDE O INÍCIO ATÉ O MÊS ANTERIOR

'C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/Empregados-Afastados-19000101-a-20220430.xlsx'

In [33]:
# ARQUIVO DE ENTRADA: base de afastados do mês anterior
for arquivo in os.listdir(DIRETORIO_ENTRA):
    if arquivo.startswith('Empregados-Afastados-'+ANO+I_MES_ANTERIOR) & arquivo.endswith('.xlsx'):
        F_RETORNO=os.path.join(DIRETORIO_ENTRA, arquivo)
# ARQUIVO DE ENTRADA: base de afastados do mês anterior
F_RETORNO

'C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/Empregados-Afastados-20220401-a-20220430.xlsx'

In [34]:
# ARQUIVO DE ENTRADA: NPS DAS LOJAS
FILE_NPS=DIRETORIO_VENDAS_NPS+'Ranking NPS.csv'
print(''+FILE_NPS)

C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/Ranking NPS.csv

In [35]:
# ARQUIVO DE ENTRADA: VENDAS DO MÊS ANTERIOR 
FILE_VENDAS=DIRETORIO_VENDAS_NPS+'RECEITA_LOJA_MENSAL.xlsx'
print(FILE_VENDAS)

C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/RECEITA_LOJA_MENSAL.xlsx

In [37]:
DIRETORIO_ANTERIOR

'C:/apuracao/TELHANORTE/2022/abr/'

In [39]:
# ARQUIVO DE ENTRADA: base de ativos MAIS ATUALIZADO gerado pela ADP
for file in os.listdir(DIRETORIO_ANTERIOR+'ORIGINAIS/'):
    if file.startswith('wr2b-') & file.endswith('.xlsx'):
        nome_base=file
#F_ATIVOS=DIRETORIO_ENTRA+nome_base
F_ATIVOS=DIRETORIO_ANTERIOR+'ORIGINAIS/'+nome_base
print(F_ATIVOS)

C:/apuracao/TELHANORTE/2022/abr/ORIGINAIS/wr2b-111909177.xlsx

In [40]:
# CARREGANDO PRÊMIOS POR GRUPO DE CARGOS 
PREMIOS=pd.read_csv(F_PREMIO_CARGO, sep=';')

In [41]:
print(PREMIOS)

      Grupo  ALVO1  ALVO2
0        GG    800   1600
1         A    600   1200
2         B    400    800
3         C    200    400
4         D    100    200
5  NAO TINA      0      0

In [42]:
print(FILE_LOJAS_TINA)

C:/apuracao/info/lojas_pilotos_rollout.csv

In [43]:
# CARREGANDO TODAS AS LOJAS TINA DO ROLL-OUT DA TELHANORTE
lojas_tina=pd.read_csv(FILE_LOJAS_TINA,sep=';', encoding='latin1')

In [44]:
#TODO Se o mês for janeiro, pegar dezembro do ano anteriorf

# if MESES.index(MES) == 0:
#     MES_ANTERIOR=MES[11]
#     DIRETORIO_ANTERIOR=DIRETORIO+str(int(float(ANO))-1)+'/'+MES_ANTERIOR+'/originais/'
#     print(DIRETORIO_ANTERIOR)

# print(DIRETORIO_ANTERIOR)

In [45]:
# CARREGANDO ALVOS COLETIVOS DAS LOJAS
print('Carregando alvos coletivos do arquivo:')
print(F_ALVOS)
alvos=pd.read_csv(F_ALVOS, sep=';', encoding='latin1')

Carregando alvos coletivos do arquivo:
C:/apuracao/info/target_store.csv

In [46]:
# FILTRANDO ALVOS DO MÊS ANTERIOR
alvos=alvos[(alvos['id_unn']==ID_UNN) & (alvos['id_mes']==int(float(ANO+I_MES_ANTERIOR)))].copy(deep=True)

In [47]:
# # TROCANDO VÍRGULA POR PONTO PARA DECIMAIS
# # CONSIDERANDO SOMENTE COLUNA DOS ALVOS 1 E 2
# alvos['target_sales_store_1']=alvos['target_sales_store_1'].str.replace(",",".").astype(float)
# alvos['target_sales_store_2']=alvos['target_sales_store_2'].str.replace(",",".").astype(float)

# # CHECAGEM
# alvos

In [48]:
FILE_VENDAS

'C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/RECEITA_LOJA_MENSAL.xlsx'

In [49]:
# CARREGANDO AS VENDAS DO MES ANTERIOR
print(FILE_VENDAS)
vendas=pd.read_excel(FILE_VENDAS) # 
if any(vendas['Loja']=="Total"): # Eliminando a linha com vendas totais
    vendas=vendas[vendas['Loja']!='Total']

# CHECAGEM
vendas

C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/RECEITA_LOJA_MENSAL.xlsx

c:\Users\C1075636\Miniconda3\envs\tina\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Loja,Unnamed: 1,Unnamed: 2,Sigla,Venda Bruta (Receita Caixa)
0,1,TN-ANHANGUERA,ANH,ANH,3290470.81
1,3,TN-MARGINAL,MGN,MGN,19755502.86
2,8,TN-PRAIA GRANDE,PGD,PGD,2457010.48
3,9,TN-SANTO ANDRÉ 1,SA1,SA1,2883713.64
4,12,TN-JUNDIAÍ,JDI,JDI,5629601.58
5,19,TN-IMIGRANTES,IMI,IMI,7651333.72
6,21,CANAL EMPRESAS,CEM,CEM,2115511.47
7,22,TN-TABOÃO,TAB,TAB,1935086.80
8,23,PRO-MARGINAL,PMG,PMG,2839836.89
9,24,TN-ARICANDUVA,ARI,ARI,8077677.11
10,25,TN-ZONA NORTE,ZNO,ZNO,6025262.19
11,26,TN-SÃO JOSÉ,SJC,SJC,4647668.70
12,27,TN-OSASCO,OSA,OSA,1615072.13
13,28,TN-SOROCABA,SOR,SOR,3281824.60
14,29,PRO-ARICANDUVA,PAR,PAR,1728748.41
15,30,TN-MORUMBI,MOR,MOR,10236851.21
16,31,TN-BELVEDERE,BEL,BEL,1797914.63
17,32,TN-GUARULHOS,GRU,GRU,3067211.96
18,34,TN-PAMPULHA,PAM,PAM,2205361.70
19,36,TN-CONTAGEM,CTG,CTG,1830317.73
20,37,TN-PIRACICABA,PIR,PIR,2140641.81
21,38,TN-D.PEDRO,DPE,DPE,1804328.79
22,39,TN-UBERLÂNDIA,UBE,UBE,1500313.55
23,40,TN-TAMBORÉ,TAM,TAM,3889825.30
24,43,TN-TATUAPÉ,TAT,TAT,3116576.28
25,48,TN-BRAGANÇA PAULISTA,BRG,BRG,1595695.62
26,51,TN-TIRADENTES,TIR,TIR,2902479.81
27,52,TN-CATUAÍ,CAT,CAT,1338749.13
28,54,TN-MARINGÁ,MGA,MGA,1621650.37
29,55,TN-PRESIDENTE PRUDENTE,PRU,PRU,2152571.37
30,56,TN-CAMPO LIMPO,CLI,CLI,2696604.22
31,57,TN-ARICANDUVA RIO DAS PEDRAS,ARP,ARP,2089312.16
32,58,CD-GUARULHOS,CDG,CDG,251961.87
33,60,CONCEITO BRASIL,CBR,CBR,1243127.82
34,62,E-COMMERCE,ECO,ECO,5876344.10
35,64,TN-SANTOS,SAN,SAN,3858814.93
36,66,TN-RAPOSO TAVARES,RAP,RAP,1949031.72
37,70,TN-WASHINGTON LUIS,WHL,WHL,1286499.53
38,71,TN-RODA VIVA,RDV,RDV,3447183.35
39,72,TN-SÃO CARLOS,SCA,SCA,1792661.11
40,73,TN-TAUBATE,TBT,TBT,1792231.17
41,74,TN-RIBEIRAO PRETO 2,RPT,RPT,1946969.77
42,75,TN_AMAZONAS,AMZ,AMZ,1070910.30
43,76,OJ-AMOREIRAS,AMO,AMO,2015594.72
44,77,TN-SUMAREZINHO,SMZ,SMZ,267080.07
45,78,TN-MOEMA,MOE,MOE,343989.02
46,81,TN-ACLIMACAO,ACL,ACL,159095.28
47,82,TN-PINHEIROS,PIN,PIN,198216.78
48,83,TN-LAPA,LPA,LPA,104914.31
49,84,TN-TUIUTI,TUI,TUI,230155.91
50,85,TN-MOOCA,MOO,MOO,92334.05
51,86,TN-LEOPOLDINA,LEO,LEO,165912.77
52,87,CENTRAL DE VENDAS,CDV,CDV,302555.75
53,88,TN-INDAIATUBA,IND,IND,383089.44

In [50]:
# CARREGANDO NPS DAS LOJAS
print('Carregando NPS das lojas')
print(FILE_NPS)
nps_lojas=pd.read_csv(FILE_NPS,sep=';')

Carregando NPS das lojas
C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/Ranking NPS.csv

In [51]:
# transformando vendas de caracteres para número
vendas = vendas[['Loja', 'Venda Bruta (Receita Caixa)']].rename(
        columns={'Loja':'cod_loja','Venda Bruta (Receita Caixa)':'Venda_Total'})

In [52]:
vendas['cod_loja']=vendas['cod_loja'].astype(float).astype(int)

In [53]:
# ORGANIZANDO VENDAS POR LOJA
loja_nps_venda_alvo=pd.merge(
    lojas_tina[['cod_loja', 'sigla_loja']],
    vendas, 
    how='left',on='cod_loja'
    )

In [54]:
# JUNTANDO NPS ÀS VENDAS
loja_nps_venda_alvo=pd.merge(
    loja_nps_venda_alvo,
    nps_lojas[['externalId','nps']].rename(
        columns={'externalId':'cod_loja'}
        ),how='left',on='cod_loja'
    )

In [55]:
# JUNTANDO OS ALVOS COLETIVOS ÀS VENDAS E NPS
loja_nps_venda_alvo=pd.merge(
    loja_nps_venda_alvo,
    alvos[['id_fil', 'id_mes', 'target_sales_store_1',
       'target_sales_store_2']].rename(
        columns={'id_fil':'cod_loja'}
        ),how='left',on='cod_loja'
    )

In [56]:
# FUNÇÃO PARA VERIFICAR SE ATINTIU ALVO1 OU ALVO2 OU NENHUM
def alvo_alcancado(venda, alvo1, alvo2):
    if venda >= alvo2:
        alvo='ALVO2'
    elif venda >= alvo1:
        alvo='ALVO1'
    else: alvo = 'NAO'
    return alvo

In [57]:
# VERIFICANDO SE A LOJA BATEU ALVO1, ALVO2 OU NÃO BATEU O ALVO
loja_nps_venda_alvo['alvo']=loja_nps_venda_alvo.apply(
    lambda x: alvo_alcancado(
        x['Venda_Total'], x['target_sales_store_1'], x['target_sales_store_2']
        ), axis=1).copy()

In [58]:
# TRANSFORMANDO OS CARACTERES DA NPS EM NÚMEROS 
# REMOVENDO % DE nps e trocando a vírgula por ponto e obter número com decimal
loja_nps_venda_alvo['nps']=loja_nps_venda_alvo['nps'].str.replace("%","")
loja_nps_venda_alvo['nps']=loja_nps_venda_alvo['nps'].str.replace(",",".").astype(float)

In [59]:
# FUNÇÃO PARA VERFICAR SE A LOJA BATEU A META DE NPS
def nps_alcancado(nps):
    global NPS_ALVO
    if nps >=NPS_ALVO:
        nps_loja='SIM'
    else: nps_loja = 'NAO'
    return nps_loja

In [60]:
# Incluindo parâmetro para verificar se a loja alcançou a NPS estabelecida
loja_nps_venda_alvo['NPS_alcancado']=loja_nps_venda_alvo['nps'].apply(
    lambda x: nps_alcancado(x)).copy()

In [61]:
# CRIANDO PLANILHA DE CHECAGEM PARA META DE NPS E VENDAS DAS LOJAS
loja_nps_venda_alvo.to_excel(FILE_CHECAGEM_LOJAS, index=False)

In [62]:
# CHECAGEM DAS LOJAS QUE ALCANÇARAM O ALVO
loja_nps_venda_alvo[
    (loja_nps_venda_alvo['alvo'] != 'NAO')
]

,cod_loja,sigla_loja,Venda_Total,nps,id_mes,target_sales_store_1,target_sales_store_2,alvo,NPS_alcancado
3,43,TAT,3116576.28,66.7,202204.0,3021009.0,3188370.0,ALVO1,SIM
5,12,JDI,5629601.58,68.6,202204.0,5201755.0,5417401.0,ALVO2,SIM
18,3,MGN,19755502.86,55.4,202204.0,19556614.0,20365671.0,ALVO1,NAO
31,48,BRG,1595695.62,67.4,202204.0,1507592.0,1625143.0,ALVO1,SIM
38,72,SCA,1792661.11,81.8,202204.0,1753628.0,1873650.0,ALVO1,SIM

In [63]:
# Obtendo somente as lojas elegíveis à premiação coletiva da Tina 
print('LOJAS ELEGÍVEIS À PREMIAÇÃO COLETIVA:')
lojas_elegiveis = loja_nps_venda_alvo[
    (loja_nps_venda_alvo['alvo'] != 'NAO') & 
    (loja_nps_venda_alvo['NPS_alcancado'] == 'SIM')
    ].copy(deep=True)
lojas_elegiveis

LOJAS ELEGÍVEIS À PREMIAÇÃO COLETIVA:

,cod_loja,sigla_loja,Venda_Total,nps,id_mes,target_sales_store_1,target_sales_store_2,alvo,NPS_alcancado
3,43,TAT,3116576.28,66.7,202204.0,3021009.0,3188370.0,ALVO1,SIM
5,12,JDI,5629601.58,68.6,202204.0,5201755.0,5417401.0,ALVO2,SIM
31,48,BRG,1595695.62,67.4,202204.0,1507592.0,1625143.0,ALVO1,SIM
38,72,SCA,1792661.11,81.8,202204.0,1753628.0,1873650.0,ALVO1,SIM

In [64]:
# Lendo faltas injustificadas dos colaboradores
print("Lendo faltas injustificadas do arquivo:")
print(F_FALTAS_MES_ANTERIOR+' tem ocorrências do dia 01 até 15 do mês anterior.')
print(F_FALTAS+' tem ocorrências do dia 16 do mês anterior até 15 do mês atual.')
faltas_inj = pd.read_excel(F_FALTAS, header=0) # Tem ocorrências do dia 16 do mes anterior até 15 do mes atual. Vou pegar somente do 16 ao final do mês anterior.
faltas_mes_anterior=pd.read_excel(F_FALTAS_MES_ANTERIOR, header=0) # para pegar as ocorrências do dia 01 até o dia 15 do mês anterior

Lendo faltas injustificadas do arquivo:
C:/apuracao/TELHANORTE/2022/abr/ORIGINAIS/PREMIACOES TINA.xlsx tem ocorrências do dia 01 até 15 do mês anterior.
C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/PREMIACOES TINA.xlsx tem ocorrências do dia 16 do mês anterior até 15 do mês atual.

In [65]:
# Juntando as bases do mês passado e delimitando para o período de apuração
todas_faltas=pd.concat([faltas_mes_anterior, faltas_inj], axis=0)
faltas = todas_faltas[(todas_faltas['DATA DA OCORRÊNCIA'] >= DATA_I) &
           (todas_faltas['DATA DA OCORRÊNCIA'] <= DATA_F)].copy()
faltas['DATA DA OCORRÊNCIA'].sort_values()

132   2022-04-01
66    2022-04-01
237   2022-04-01
77    2022-04-01
93    2022-04-01
         ...
288   2022-04-30
302   2022-04-30
11    2022-04-30
227   2022-04-30
37    2022-04-30
Name: DATA DA OCORRÊNCIA, Length: 303, dtype: datetime64[ns]

In [66]:
# Renomeando a coluna da MATRICULA nas faltas 
faltas.rename(columns={'MATR EMPR':'MATRICULA'}, inplace=True)

In [67]:
# CHECAGEM
# Somente para verificar se o colaborador teve falta na período
faltas

,PERIODO - DTINI,PERIODO - DTFIM,EMPRESA,DATA DA OCORRÊNCIA,COD ESTAB,NOME ESTAB,COD CR,NOME CR,CÓDIGO DO CENTRO CUSTO CONTABILIDADE,MATR CHEFIA,NOME CHEFIA,MATRICULA,NOME EMPPR,FUNCAO-DENOMINACAO,COD VERBA,DESCRICAO VERBA,VALOR
14,2022-03-16,2022-04-15,1,2022-04-02,32,PAM,344402,PAM - OPERACOES LOJA,344402,11014,REGINALDO DIAS DO NASCIMENTO,20159,ADAILZA SANTOS DA SILVA,Lider de Caixa,9005,Falta Injustificada,7.33
15,2022-03-16,2022-04-15,1,2022-04-03,32,PAM,344402,PAM - OPERACOES LOJA,344402,11014,REGINALDO DIAS DO NASCIMENTO,20159,ADAILZA SANTOS DA SILVA,Lider de Caixa,4452,Falta PPR,7.33
16,2022-03-16,2022-04-15,1,2022-04-04,32,PAM,344402,PAM - OPERACOES LOJA,344402,11014,REGINALDO DIAS DO NASCIMENTO,20159,ADAILZA SANTOS DA SILVA,Lider de Caixa,9005,Falta Injustificada,7.33
17,2022-03-16,2022-04-15,1,2022-04-05,32,PAM,344402,PAM - OPERACOES LOJA,344402,11014,REGINALDO DIAS DO NASCIMENTO,20159,ADAILZA SANTOS DA SILVA,Lider de Caixa,9005,Falta Injustificada,7.33
18,2022-03-16,2022-04-15,1,2022-04-06,32,PAM,344402,PAM - OPERACOES LOJA,344402,11014,REGINALDO DIAS DO NASCIMENTO,20159,ADAILZA SANTOS DA SILVA,Lider de Caixa,9005,Falta Injustificada,7.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,2022-04-16,2022-05-15,1,2022-04-30,19,ZNO,254403,ZNO - VENDAS,254403,16765,MARCOS ALBERTO LUCIANO DE LIMA,15585,WAGNER KRUGER,Vendedor(a),7302,Faltas Injustificadas Comissionados,9.00
302,2022-04-16,2022-05-15,1,2022-04-30,10,MGN,174403,MGN - VENDAS,174403,27460,FERNANDO MENDES DE SOUSA,131,WALTER GONCALVES FONTES,Vendedor(a),7302,Faltas Injustificadas Comissionados,7.33
303,2022-04-16,2022-05-15,1,2022-04-17,14,IMI,204403,IMI - VENDAS,204403,10874,ROSIANE MARIA LUNA FERNANDES BALDI,11899,WILIAN ROBSON SOUZA,Vendedor(a),4452,Falta PPR,7.33
304,2022-04-16,2022-05-15,1,2022-04-25,18,PMG,234406,PMG - DEPOSITO LOJA,234406,8513,RENE CESAR MONTEIRO,26609,WILLIAM OTONI QUARESMA DA SILV,Assessor de Operações I,9005,Falta Injustificada,7.33
305,2022-04-16,2022-05-15,1,2022-04-29,36,UBE,414403,UBE - VENDAS,414403,11995,JULIANA APARECIDA CAMILO,28233,YGOR VINICIUS SILVA CORDEIRO,Vendedor(a),7302,Faltas Injustificadas Comissionados,7.33

In [68]:
# Lendo base de ativos
print("Lendo base de ativos no arquivo:")
print(F_ATIVOS)
#base_ativos = pd.read_excel(F_ATIVOS, header=0) # 
base_ativos = pd.read_excel(F_ATIVOS) #

Lendo base de ativos no arquivo:
C:/apuracao/TELHANORTE/2022/abr/ORIGINAIS/wr2b-111909177.xlsx

In [69]:
# Removendo espaços em branco do nome da coluna 
base_ativos.columns = base_ativos.columns.str.strip()
print(base_ativos.columns)

Index(['Estabelecimento - Código', 'Matrícula', 'Nome - Primeiro Nome',
       'Nome - Sobrenome', 'Cargo - Código', 'Cargo - Nome',
       'Data de Nascimento', 'Data da Admissão',
       'Situação do Empregado - Status', 'Escala - Código', 'Escala - Nome',
       'Estabelecimento - Nome', 'Vínculo Empregatício - Código',
       'Vínculo Empregatício - Nome', 'Chefia Imediata - Matrícula',
       'Centro de Resultado - Código', 'Centro de Resultado - Nome'],
      dtype='object')

In [70]:
# MANTENDO APENAS A SIGLA DAS LOJAS
base_ativos['Estabelecimento - Nome']=base_ativos['Estabelecimento - Nome'].apply(
    lambda x: x.strip()[-3:]
)

In [71]:
# ELIMINA ESPAÇOS EM BRANCO ANTES E DEPOIS DA DATA
base_ativos['Data da Admissão']=base_ativos['Data da Admissão'].apply(
    lambda x: x.strip()
    )

In [72]:
# Mantendo apenas Telhanorte
base_ativos=base_ativos[base_ativos['Estabelecimento - Código']<510000]

In [73]:
# Pegando da base de ativos somente parâmetros/colunas necessários 
ativos=base_ativos[[
    'Matrícula', 
    'Nome - Primeiro Nome',
    'Nome - Sobrenome', 
    'Cargo - Nome',
    'Data da Admissão',
    'Situação do Empregado - Status',
    'Estabelecimento - Nome',
    'Centro de Resultado - Código'
    ]].copy(deep=True)

In [74]:
# RENOMEANDO OS PARÂMETROS/COLUNAS DA BASE DE ativos DA esquerda para direita {'ESQUERDA':'DIREITA'}
RENOMEA={
    'Matrícula':'MATRICULA', 
    'Nome - Primeiro Nome':'NOME',
    'Nome - Sobrenome':'SOBRENOME', 
    'Cargo - Nome':'CARGO',
    'Data da Admissão':'DATA_ADMISSAO',
    'Situação do Empregado - Status':'STATUS',
    'Estabelecimento - Nome':'LOJA'
}

ativos.rename(columns=RENOMEA, inplace=True)

In [75]:
# FORMATO DE DATA dd/mm/aaaa
ativos['DATA_ADMISSAO']=pd.to_datetime(ativos['DATA_ADMISSAO'], format='%d/%m/%Y')

In [76]:
# Mantendo apenas colaboradores da loja da MGN, excluindo sede
ativos_nao_MGN=ativos[ativos['LOJA']!='MGN']

In [77]:
# Toda a MGN
ativos_MGN=ativos[ativos['LOJA']=='MGN'].copy(deep=True)
loja_MGN=ativos_MGN[(ativos_MGN['Centro de Resultado - Código']==808568) |
    ((ativos_MGN['Centro de Resultado - Código']>=174000) & 
    (ativos_MGN['Centro de Resultado - Código']<=174999) )  
    ].copy(deep=True)

In [78]:
# JUNTANDO BASE DE ATIVOS SOMENTE DAS LOJAS e a LOJA DA MARGINAL
ativos_lojas=pd.concat([ativos_nao_MGN, loja_MGN], ignore_index=True)

In [79]:
# CRIANDO BASE tina A PARTIR DA BASE DE ATIVOS DO MÊS ANTERIOR 
# 
tina=ativos_lojas[ativos_lojas['LOJA'].isin(lojas_tina['sigla_loja'][lojas_tina['id_unn']==ID_UNN])].copy(deep=True)

In [80]:
#  Função para calcular os dias ADMITIDOS dentro do período apurado
def admitidos_no_mes(data_admissao):
    global DATA_I, DATA_F
    if data_admissao > DATA_F:
        dias_admitidos = 0
    elif data_admissao <= DATA_I :
        dias_admitidos=DATA_F.day
    else:
        dias_admitidos=(DATA_F-data_admissao).days+1
    return dias_admitidos

In [81]:
(DATA_F-tina['DATA_ADMISSAO'].iloc[0]).days

11291

In [82]:
# CALCULANDO QUANTOS DIAS O FUNCIONÁRIO ESTÁ ADMITIDO NO MÊS DA APURAÇÃO
tina['DIAS_ADMITIDOS']=tina['DATA_ADMISSAO'].apply(
    lambda x: admitidos_no_mes(x)
    ).copy()

In [83]:
# INCLUINDO INFORMAÇÃO SE O COLABORADOR ESTÁ ADMITIDO HÁ MAIS DE 15 DIAS DO PERÍODO DE APURAÇÃO
tina['MAIS_DE15DIAS_ADMITIDOS']=np.where(tina['DIAS_ADMITIDOS']>=MEIO_MES,"SIM", "NAO")

In [84]:
# LIMBANDO ESPAÇOS EM BRANCO DO STATUS
tina['STATUS']=tina['STATUS'].apply(
    lambda x: x.strip()
    )

In [85]:
tina['STATUS'].unique()

array(['ATIVO', 'SUSPENSÃO', 'Auxilio', 'Férias', 'Suspensão', 'Licença',
       'Seguro', 'Atestado', 'Demissão'], dtype=object)

In [86]:
# Elimina espaços em branco dos CARGOs dos funcionários 
tina['CARGO']=tina['CARGO'].apply(
    lambda x: x.strip()
)
# CHECAGEM
tina['CARGO'].unique()

array(['Enc Depósito', 'Ger Geral I', 'Ger Operacional II',
       'Ass Manut Serv Gerais', 'Ger Geral II', 'Vendedor(a)',
       'Assessor de Operações II', 'Enc de Caixa', 'Sup Operacional',
       'Repositor(a)', 'Conferente', 'Operador Empilhadeira',
       'Aux Manutenção', 'Sup de Vendas', 'Ger de Vendas I',
       'Ass Serviços ao Cliente', 'Ass Recebimento',
       'Assessor de Operações I', 'ASSESSOR DE LOJA', 'Ass de Expedição',
       'Sup de Produto', 'Vendedor(a) Especialista', 'Enc de Produto',
       'Enc SAC', 'Operador(a) Caixa', 'Lider de Caixa',
       'Ger Operacional I', 'Ger Geral III', 'Ger de Produto II',
       'ANL RH REGIONAL PL', 'Enc CTN', 'Ass Prevenção de Perdas',
       'Enc Prevenção de Perda', 'Sup Administrativo',
       'Vendedor(a) Especialista Lider', 'Ger de Vendas II',
       'Ass Depósito', 'Oficial Manutenção Eletricista',
       'Ger de Vendas III', 'Atendente de Loja', 'Vendedor(a) Projetista',
       'DESIGNER PROJETISTA', 'Ger de Produto I', 'Anl de Logística Jr',
       'Gerente Operacional', 'Sup deProduto I',
       'Técnico Seguranca Trabalho Pl', 'Menor Aprendiz',
       'Ass Serviço ao Cliente', 'Consultor de Vendas Externas',
       'Estagiário(a)', 'Ass Departamento Pessoal', 'ENC DE OPERACOES',
       'Enc Serviços ao Cliente', 'Ass Administrativo', 'GER GERAL SR',
       'Sup Caixa', 'ASSESSOR DE OPERACOES', 'Técnico Projetista'],
      dtype=object)

In [87]:
# INCLUINDO ELEGIBILIDADE DA LOJA
tina['LOJA_ELEGIVEL']=np.where(tina['LOJA'].isin(lojas_elegiveis['sigla_loja']),'SIM','NAO')

In [88]:
tina[(tina['DIAS_ADMITIDOS']<0) ]

Empty DataFrame
Columns: [MATRICULA, NOME, SOBRENOME, CARGO, DATA_ADMISSAO, STATUS, LOJA, Centro de Resultado - Código, DIAS_ADMITIDOS, MAIS_DE15DIAS_ADMITIDOS, LOJA_ELEGIVEL]
Index: []

JUNTANDO BASE DE AFASTADOS E DE RETORNOS DO MÊS DE APURAÇÃO

In [89]:
# BASE DE DATA DE RETORNO DOS COLABORADORES 
# 
# Lendo base de retorno
print("Lendo base de retorno no arquivo:")
print(F_RETORNO)
base_retorno = pd.read_excel(F_RETORNO) # afastados=

Lendo base de retorno no arquivo:
C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/Empregados-Afastados-20220401-a-20220430.xlsx

In [90]:
# BASE DE AFASTADOS 
# 
# Lendo base de afastados
print("Lendo base de afastados no arquivo:")
print(F_AFASTADOS)
base_afastados = pd.read_excel(F_AFASTADOS) # afastados=

Lendo base de afastados no arquivo:
C:/apuracao/TELHANORTE/2022/mai/ORIGINAIS/Empregados-Afastados-19000101-a-20220430.xlsx

In [91]:
base_afastados.columns

Index(['Empresa', 'Código do Estabelecimento', 'Descrição do Estabelecimento',
       'Matrícula', 'Nome', 'Função', 'Centro de Resultado',
       'Descrição de Centro de Resultado', 'Número de Dias',
       'Data de Admissão', 'Data de Afastamento', 'Data de Retorno',
       'Tipo de Afastamento', 'Motivo Interno do Afastamento',
       'Data Previsão Perícia INSS', 'Protocolo Agendamento Perícia',
       'Número Benefício'],
      dtype='object')

In [92]:
base_retorno.columns

Index(['Empresa', 'Código do Estabelecimento', 'Descrição do Estabelecimento',
       'Matrícula', 'Nome', 'Função', 'Centro de Resultado',
       'Descrição de Centro de Resultado', 'Número de Dias',
       'Data de Admissão', 'Data de Afastamento', 'Data de Retorno',
       'Tipo de Afastamento', 'Motivo Interno do Afastamento',
       'Data Previsão Perícia INSS', 'Protocolo Agendamento Perícia',
       'Número Benefício'],
      dtype='object')

In [93]:
base_retorno

,Empresa,Código do Estabelecimento,Descrição do Estabelecimento,Matrícula,Nome,Função,Centro de Resultado,Descrição de Centro de Resultado,Número de Dias,Data de Admissão,Data de Afastamento,Data de Retorno,Tipo de Afastamento,Motivo Interno do Afastamento,Data Previsão Perícia INSS,Protocolo Agendamento Perícia,Número Benefício
0,1,57,Saint-Gobain Distribuição Brasil Ltda - SAN,27539,ABDIAS DA SILVA PEREIRA JUNIOR,ASSESSOR DE LOJA,574402,SAN - Operações Loja,38,11/11/2019,06/03/2022,13/04/2022,SC - Suspensão Contrato de Trabalho,NaN,NaN,NaN,NaN
1,1,49,Saint-Gobain Distribuição Brasil Ltda - ARP,28523,ADALBERTO CAVALCANTE SOUSA,ASSESSOR DE LOJA,534402,ARP - OPERACOES LOJA,20,01/12/2020,04/04/2022,24/04/2022,FE - Férias,NaN,NaN,NaN,NaN
2,1,40,Saint-Gobain Distribuição Brasil Ltda - CLI,28545,ADELSON DOS SANTOS JUNIOR,Assessor de Operações I,524406,CLI - DEPOSITO LOJA,30,07/12/2020,17/03/2022,16/04/2022,FE - Férias,NaN,NaN,NaN,NaN
3,1,14,Saint-Gobain Distribuição Brasil Ltda - IMI,28524,ADRIANA PEREIRA MILITAO,ASSESSOR DE LOJA,204402,IMI - OPERACOES LOJA,10,01/12/2020,29/03/2022,08/04/2022,AT - Atestado Médico,NaN,NaN,NaN,NaN
4,1,55,Saint-Gobain Distribuicao Brasil Ltda - RAP,23792,ADRIANA PUPIN,Vendedor(a),554403,RAP - Vendas,30,11/02/2016,18/03/2022,17/04/2022,FE - Férias,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,4,44,TUMELERO MATERIAIS DE CONSTRUCAO LTDA - SMA,12413,SUZANA GOMES DE SOUZA,FISCAL DE LOJA,248404,SMA - SEGURANCA,30,09/03/2020,09/03/2022,08/04/2022,FE - Férias,NaN,NaN,NaN,NaN
540,4,1,TUMELERO MATERIAIS DE CONSTRUCAO LTDA - MTZ,11732,VALDECIR RENER DA CRUZ,VENDEDOR(A) TELEVENDAS,838401,MTZ - TELEVENDAS - TLV,378,10/10/2017,19/03/2021,01/04/2022,BE - Auxilio Doença,NaN,NaN,NaN,NaN
541,4,1,TUMELERO MATERIAIS DE CONSTRUCAO LTDA - MTZ,10642,VERUSA CARISELI CORREIA DOS SANTOS,CAIXA CREDIARISTA,208403,MTZ - CAIXA,30,17/11/2014,08/03/2022,07/04/2022,FE - Férias,NaN,NaN,NaN,NaN
542,4,7,TUMELERO MATERIAIS DE CONSTRUCAO LTDA - NHA,23912,WILLIAM BERNARDES CANCIANI,AUXILIAR DE EXPEDICAO I,408405,NHA - EXPEDICAO,10,02/03/2022,17/04/2022,27/04/2022,AT - Atestado Médico,NaN,NaN,NaN,NaN
543,4,77,TUMELERO MATERIAIS DE CONSTRUCAO LTDA - PFO,11905,WOLNI FOLLMER,OPERADOR DE EMPILHADEIRA LOJA,718405,PFO - EXPEDICAO,3,02/05/2018,11/04/2022,14/04/2022,AT - Atestado Médico,NaN,NaN,NaN,NaN

In [94]:
# PARÂMETROS NECESSÁRIOS DOS AFASTADOS
PARAMETROS=[
    'Empresa', 
    'Descrição do Estabelecimento', 
    'Matrícula', 
    'Nome',
    'Função', 
    'Centro de Resultado',
    'Número de Dias', 
    'Data de Admissão', 
    'Data de Afastamento', 
    'Data de Retorno',
    'Tipo de Afastamento'
]

In [95]:
# JUNTANDO BASE DE AFASTADOS COM O DE RETORNO
#     Somente dos parâmetros necessários
afastados = pd.concat(
    [base_afastados[PARAMETROS].copy(deep=True), 
    base_retorno[PARAMETROS].copy(deep=True)], 
    ignore_index=True
    )

In [96]:
afastados['Data de Admissão']=pd.to_datetime(afastados['Data de Admissão'], format="%d/%m/%Y")
afastados['Data de Afastamento']=pd.to_datetime(afastados['Data de Afastamento'], format="%d/%m/%Y")
afastados['Data de Retorno']=pd.to_datetime(afastados['Data de Retorno'], format="%d/%m/%Y")

In [97]:
# Para renomear  os parâmetros da base de afastados
RENOMEA={
    'Empresa': 'EMPRESA',
    'Descrição do Estabelecimento': 'LOJA', 
    'Matrícula':'MATRICULA', 
    'Nome':'NOME',
    'Data de Admissão':'DATA_ADMISSAO', 
    'Data de Afastamento':'DATA_AFASTAMENTO', 
    'Data de Retorno':'DATA_RETORNO',   
    'Tipo de Afastamento':'MOTIVO'
    }

# Renomeando as colunas da base de afastados com nome da direita pelo da esquerda
afastados.rename(columns=RENOMEA, inplace=True)

In [98]:
# EXTRAINDO SIGLA DA LOJA
afastados['LOJA']=afastados['LOJA'].apply(
    lambda x: x.strip()[-3:]
)
afastados

,EMPRESA,LOJA,MATRICULA,NOME,Função,Centro de Resultado,Número de Dias,DATA_ADMISSAO,DATA_AFASTAMENTO,DATA_RETORNO,MOTIVO
0,1,ARI,27673,ABIGAIU SANTOS DE ANDRADE,ASSESSOR DE LOJA,244402,30,2019-12-13,2022-04-07,2022-05-07,FE - Férias
1,1,RPT,27193,ADEILTON VIEIRA DA SILVA,ASSESSOR DE LOJA,634403,30,2019-08-05,2022-04-07,2022-05-07,FE - Férias
2,1,JDI,7792,ADONEL OSORIO DE SOUSA,Repositor(a),114406,2459,2004-11-12,2015-08-06,NaT,SC - Suspensão Contrato de Trabalho
3,1,PGD,28348,ADONIRA SANTOS SANTIAGO,ASSESSOR DE LOJA,124403,30,2020-10-19,2022-04-11,2022-05-11,FE - Férias
4,1,OSA,24735,ADRIANA DE MELO RIBEIRO,Lider de Caixa,274402,30,2017-02-20,2022-04-01,2022-05-01,FE - Férias
...,...,...,...,...,...,...,...,...,...,...,...
994,4,SMA,12413,SUZANA GOMES DE SOUZA,FISCAL DE LOJA,248404,30,2020-03-09,2022-03-09,2022-04-08,FE - Férias
995,4,MTZ,11732,VALDECIR RENER DA CRUZ,VENDEDOR(A) TELEVENDAS,838401,378,2017-10-10,2021-03-19,2022-04-01,BE - Auxilio Doença
996,4,MTZ,10642,VERUSA CARISELI CORREIA DOS SANTOS,CAIXA CREDIARISTA,208403,30,2014-11-17,2022-03-08,2022-04-07,FE - Férias
997,4,NHA,23912,WILLIAM BERNARDES CANCIANI,AUXILIAR DE EXPEDICAO I,408405,10,2022-03-02,2022-04-17,2022-04-27,AT - Atestado Médico
998,4,PFO,11905,WOLNI FOLLMER,OPERADOR DE EMPILHADEIRA LOJA,718405,3,2018-05-02,2022-04-11,2022-04-14,AT - Atestado Médico

In [99]:
afastados[afastados['MATRICULA']==1187]

Empty DataFrame
Columns: [EMPRESA, LOJA, MATRICULA, NOME, Função, Centro de Resultado, Número de Dias, DATA_ADMISSAO, DATA_AFASTAMENTO, DATA_RETORNO, MOTIVO]
Index: []

In [100]:
# AFASTADOS SOMENTE EMPRESA SELECIONADA ACIMA ID_UNN
afastados=afastados[afastados['EMPRESA']==ID_UNN]

In [101]:
# SOMENTE LOJAS TINA DA TELHANORTE
lojas_tina_telha=lojas_tina[['cod_loja', 'sigla_loja']][lojas_tina['id_unn']==1]

In [102]:
# AFASTADOS SOMENTE TINA
afastados=afastados[afastados['LOJA'].isin(lojas_tina_telha['sigla_loja'])].copy(deep=True)
afastados

,EMPRESA,LOJA,MATRICULA,NOME,Função,Centro de Resultado,Número de Dias,DATA_ADMISSAO,DATA_AFASTAMENTO,DATA_RETORNO,MOTIVO
0,1,ARI,27673,ABIGAIU SANTOS DE ANDRADE,ASSESSOR DE LOJA,244402,30,2019-12-13,2022-04-07,2022-05-07,FE - Férias
1,1,RPT,27193,ADEILTON VIEIRA DA SILVA,ASSESSOR DE LOJA,634403,30,2019-08-05,2022-04-07,2022-05-07,FE - Férias
2,1,JDI,7792,ADONEL OSORIO DE SOUSA,Repositor(a),114406,2459,2004-11-12,2015-08-06,NaT,SC - Suspensão Contrato de Trabalho
3,1,PGD,28348,ADONIRA SANTOS SANTIAGO,ASSESSOR DE LOJA,124403,30,2020-10-19,2022-04-11,2022-05-11,FE - Férias
4,1,OSA,24735,ADRIANA DE MELO RIBEIRO,Lider de Caixa,274402,30,2017-02-20,2022-04-01,2022-05-01,FE - Férias
...,...,...,...,...,...,...,...,...,...,...,...
869,1,IMI,11899,WILIAN ROBSON SOUZA,Vendedor(a),204403,4,2008-08-15,2022-04-07,2022-04-11,AT - Atestado Médico
870,1,PAM,19814,WILLIAN DE SOUZA OLIVEIRA,Assessor de Operações II,344406,30,2013-03-01,2022-03-07,2022-04-06,FE - Férias
871,1,SAN,26774,YASMIN NOBREGA DE MESQUITA CAVALCANTE,ASSESSOR DE LOJA,574402,30,2019-02-18,2022-03-07,2022-04-06,FE - Férias
872,1,UBE,28233,YGOR VINICIUS SILVA CORDEIRO,Vendedor(a),414403,30,2020-10-05,2022-03-28,2022-04-27,FE - Férias
873,1,PMG,26627,YURI WALLENTIN DE SOUSA FERREIRA,ASSESSOR DE LOJA,234402,15,2018-12-12,2022-03-17,2022-04-01,AT - Atestado Médico

In [103]:
afastados[afastados['LOJA']=='SAN']

,EMPRESA,LOJA,MATRICULA,NOME,Função,Centro de Resultado,Número de Dias,DATA_ADMISSAO,DATA_AFASTAMENTO,DATA_RETORNO,MOTIVO
38,1,SAN,9716,ANDERSON RIBEIRO NASCIMENTO,Vendedor(a),574403,1299,2006-12-14,2018-10-09,NaT,BE - Auxilio Doença
78,1,SAN,28421,CRISTINA MENDES DE ABREU,ASSESSOR DE LOJA,574403,14,2020-11-09,2022-04-23,2022-05-07,AT - Atestado Médico
115,1,SAN,10361,ENILSON DA ROCHA CORREIA,Ger de Produto II,574401,73,2007-05-02,2022-02-16,NaT,BE - Auxilio Doença
180,1,SAN,20825,JOSY CRISTIANE LOPES RIBEIRO DOS SANTOS,Lider de Caixa,574402,26,2013-11-01,2022-04-04,NaT,BE - Auxilio Doença
297,1,SAN,24386,RONEY BOER,Vendedor(a),574403,30,2016-11-07,2022-04-26,2022-05-26,FE - Férias
319,1,SAN,25718,TAYNA DA SILVA LIMA,Vendedor(a),574403,30,2018-03-20,2022-04-28,2022-05-28,FE - Férias
342,1,SAN,26774,YASMIN NOBREGA DE MESQUITA CAVALCANTE,ASSESSOR DE LOJA,574402,120,2019-02-18,2022-04-06,2022-08-04,LM - Licença Maternidade
455,1,SAN,27539,ABDIAS DA SILVA PEREIRA JUNIOR,ASSESSOR DE LOJA,574402,38,2019-11-11,2022-03-06,2022-04-13,SC - Suspensão Contrato de Trabalho
518,1,SAN,26390,CARLOS PAES DA CRUZ FILHO,Vendedor(a),574403,30,2018-10-11,2022-03-28,2022-04-27,FE - Férias
674,1,SAN,20825,JOSY CRISTIANE LOPES RIBEIRO DOS SANTOS,Lider de Caixa,574402,14,2013-11-01,2022-03-21,2022-04-04,AT - Atestado Médico
710,1,SAN,28723,LUCAS FELIX DA SILVA,Assessor de Operações I,574406,3,2021-01-11,2022-04-11,2022-04-14,AT - Atestado Médico
715,1,SAN,21010,LUCIANA SILENE MANUEL SOARES,ASSESSOR DE LOJA,574402,30,2013-12-10,2022-03-10,2022-04-09,FE - Férias
743,1,SAN,24499,MARIA NADJA SANTOS DIAS,Ger de Vendas I,574401,20,2016-12-12,2022-03-28,2022-04-17,FE - Férias
750,1,SAN,26495,MARILIA APARECIDA LOURENCO NAVARRO,Vendedor(a),574403,30,2018-11-12,2022-03-28,2022-04-27,FE - Férias
832,1,SAN,28411,TAMARA DAIANE FERREIRA,Ass Serviços ao Cliente,574402,30,2020-11-09,2022-03-07,2022-04-06,FE - Férias
871,1,SAN,26774,YASMIN NOBREGA DE MESQUITA CAVALCANTE,ASSESSOR DE LOJA,574402,30,2019-02-18,2022-03-07,2022-04-06,FE - Férias

In [104]:
#  Função para calcular os dias de afastamento dentro do período apurado
def afastamento_do_mes(data_afastamento, data_retorno):
    global DATA_I, DATA_F
    if data_afastamento < DATA_I and data_retorno < DATA_I:
        dias_afastados=0
    elif data_afastamento >= DATA_I and data_retorno <= DATA_F:
        dias_afastados=(data_retorno-data_afastamento).days
    elif (data_afastamento < DATA_I or pd.isnull(data_afastamento))  and data_retorno <= DATA_F:
        dias_afastados=(data_retorno-DATA_I).days
    elif data_afastamento >= DATA_I and (data_retorno > DATA_F or pd.isnull(data_retorno)):
        dias_afastados=(DATA_F-data_afastamento).days+1
    elif (data_afastamento < DATA_I or pd.isnull(data_afastamento)) and (data_retorno > DATA_F or pd.isnull(data_retorno)):
        dias_afastados=(DATA_F.day)
    elif (data_afastamento < DATA_I or pd.isnull(data_afastamento)) and (data_retorno < DATA_I):
        dias_afastados=(DATA_F.day-DATA_F.day)
    else:
        print("ERRO")
        dias_afastados=0

    return dias_afastados

In [105]:
# Contando os dias de afastamento para cada período de afastamento considerando o período de apuração
afastados['dias_afastados']=afastados.apply(
    lambda x: afastamento_do_mes(x['DATA_AFASTAMENTO'],x['DATA_RETORNO']), axis=1)

In [106]:
afastados[afastados['LOJA']=='SAN']

,EMPRESA,LOJA,MATRICULA,NOME,Função,Centro de Resultado,Número de Dias,DATA_ADMISSAO,DATA_AFASTAMENTO,DATA_RETORNO,MOTIVO,dias_afastados
38,1,SAN,9716,ANDERSON RIBEIRO NASCIMENTO,Vendedor(a),574403,1299,2006-12-14,2018-10-09,NaT,BE - Auxilio Doença,30
78,1,SAN,28421,CRISTINA MENDES DE ABREU,ASSESSOR DE LOJA,574403,14,2020-11-09,2022-04-23,2022-05-07,AT - Atestado Médico,8
115,1,SAN,10361,ENILSON DA ROCHA CORREIA,Ger de Produto II,574401,73,2007-05-02,2022-02-16,NaT,BE - Auxilio Doença,30
180,1,SAN,20825,JOSY CRISTIANE LOPES RIBEIRO DOS SANTOS,Lider de Caixa,574402,26,2013-11-01,2022-04-04,NaT,BE - Auxilio Doença,27
297,1,SAN,24386,RONEY BOER,Vendedor(a),574403,30,2016-11-07,2022-04-26,2022-05-26,FE - Férias,5
319,1,SAN,25718,TAYNA DA SILVA LIMA,Vendedor(a),574403,30,2018-03-20,2022-04-28,2022-05-28,FE - Férias,3
342,1,SAN,26774,YASMIN NOBREGA DE MESQUITA CAVALCANTE,ASSESSOR DE LOJA,574402,120,2019-02-18,2022-04-06,2022-08-04,LM - Licença Maternidade,25
455,1,SAN,27539,ABDIAS DA SILVA PEREIRA JUNIOR,ASSESSOR DE LOJA,574402,38,2019-11-11,2022-03-06,2022-04-13,SC - Suspensão Contrato de Trabalho,12
518,1,SAN,26390,CARLOS PAES DA CRUZ FILHO,Vendedor(a),574403,30,2018-10-11,2022-03-28,2022-04-27,FE - Férias,26
674,1,SAN,20825,JOSY CRISTIANE LOPES RIBEIRO DOS SANTOS,Lider de Caixa,574402,14,2013-11-01,2022-03-21,2022-04-04,AT - Atestado Médico,3
710,1,SAN,28723,LUCAS FELIX DA SILVA,Assessor de Operações I,574406,3,2021-01-11,2022-04-11,2022-04-14,AT - Atestado Médico,3
715,1,SAN,21010,LUCIANA SILENE MANUEL SOARES,ASSESSOR DE LOJA,574402,30,2013-12-10,2022-03-10,2022-04-09,FE - Férias,8
743,1,SAN,24499,MARIA NADJA SANTOS DIAS,Ger de Vendas I,574401,20,2016-12-12,2022-03-28,2022-04-17,FE - Férias,16
750,1,SAN,26495,MARILIA APARECIDA LOURENCO NAVARRO,Vendedor(a),574403,30,2018-11-12,2022-03-28,2022-04-27,FE - Férias,26
832,1,SAN,28411,TAMARA DAIANE FERREIRA,Ass Serviços ao Cliente,574402,30,2020-11-09,2022-03-07,2022-04-06,FE - Férias,5
871,1,SAN,26774,YASMIN NOBREGA DE MESQUITA CAVALCANTE,ASSESSOR DE LOJA,574402,30,2019-02-18,2022-03-07,2022-04-06,FE - Férias,5

In [107]:
# CHECAGEM
afastados.to_excel(FILE_CHECAGEM_AFASTADOS, index=False)

In [108]:
# CHECAGEM
# Verificando se há matrículas com mais de um afastamento no período apurado
afastados[afastados['MATRICULA']==2579]

Empty DataFrame
Columns: [EMPRESA, LOJA, MATRICULA, NOME, Função, Centro de Resultado, Número de Dias, DATA_ADMISSAO, DATA_AFASTAMENTO, DATA_RETORNO, MOTIVO, dias_afastados]
Index: []

In [109]:
# CHECAGEM
#  Para verificar o afastamento de uma matrícula específica
afastados[afastados['MATRICULA']==28143]

,EMPRESA,LOJA,MATRICULA,NOME,Função,Centro de Resultado,Número de Dias,DATA_ADMISSAO,DATA_AFASTAMENTO,DATA_RETORNO,MOTIVO,dias_afastados
80,1,MGN,28143,DAIANE DE SOUZA MIGUEL,ASSESSOR DE LOJA,174402,17,2020-09-01,2022-04-13,NaT,BE - Auxilio Doença,18
534,1,MGN,28143,DAIANE DE SOUZA MIGUEL,ASSESSOR DE LOJA,174402,15,2020-09-01,2022-03-29,2022-04-13,AT - Atestado Médico,12

In [110]:
# SOMANDO OS DIAS AFASTADOS POR MATRÍCULA
dias_afastados_por_matricula=afastados.groupby(
    ['EMPRESA', 'LOJA','MATRICULA', 'NOME']
    )['dias_afastados'].sum().reset_index(name='dias_afastados_totais')

In [111]:
dias_afastados_por_matricula[dias_afastados_por_matricula['MATRICULA']==6068]

     EMPRESA LOJA  MATRICULA                      NOME  dias_afastados_totais
369        1  PMG       6068  LINDOVAL MATIAS DA SILVA                     30

In [112]:
# dias_afastados_por_matricula_telha=pd.merge(
#     dias_afastados_por_matricula[['LOJA', 'MATRICULA', 'dias_afastados_totais']
#         ][(dias_afastados_por_matricula['EMPRESA']==ID_UNN) &
#         (dias_afastados_por_matricula['LOJA'].isin(lojas_tina['cod_loja']))
#         ],
#     lojas_tina[['cod_loja', 'sigla_loja']][lojas_tina['id_unn']==ID_UNN].rename(columns={
#         'cod_loja':'COD_LOJA',
#         'sigla_loja':'LOJA'}),
#     how='left',
#     on='COD_LOJA'
#)

In [113]:
# pd.merge(
#     dias_afastados_por_matricula[['COD_LOJA', 'MATRICULA', 'dias_afastados_totais']
#         ][(dias_afastados_por_matricula['EMPRESA']==ID_UNN) &
#         (dias_afastados_por_matricula['COD_LOJA'].isin(lojas_tina['cod_loja']))
#         ],
#     lojas_tina[['cod_loja', 'sigla_loja']][lojas_tina['id_unn']==ID_UNN].rename(columns={
#         'cod_loja':'COD_LOJA',
#         'sigla_loja':'LOJA'}),
#     how='left',
#     on='COD_LOJA'
# )

In [114]:
tina[tina['LOJA']=='SAN']

,MATRICULA,NOME,SOBRENOME,CARGO,DATA_ADMISSAO,STATUS,LOJA,Centro de Resultado - Código,DIAS_ADMITIDOS,MAIS_DE15DIAS_ADMITIDOS,LOJA_ELEGIVEL
16,2579,MARLENE,DE SANTANA,Enc de Caixa,1999-06-07,ATIVO,SAN,574402,30,SIM,NAO
71,6591,ROSANA,FERNANDES,Vendedor(a),2003-08-04,ATIVO,SAN,574403,30,SIM,NAO
73,6790,GERALDO,DA COSTA,Vendedor(a),2003-11-03,ATIVO,SAN,574403,30,SIM,NAO
134,9716,ANDERSON,NASCIMENTO,Vendedor(a),2006-12-14,Auxilio,SAN,574403,30,SIM,NAO
156,10361,ENILSON,CORREIA,Ger de Produto II,2007-05-02,Auxilio,SAN,574401,30,SIM,NAO
457,18882,ADELSON,DE SOUZA,Vendedor(a),2012-07-02,ATIVO,SAN,574403,30,SIM,NAO
547,20765,LUIZ,GOIS,Operador Empilhadeira,2013-10-15,ATIVO,SAN,574406,30,SIM,NAO
550,20825,JOSY,DOS SANTOS,Lider de Caixa,2013-11-01,Auxilio,SAN,574402,30,SIM,NAO
556,20948,LILIAN,LOPES,Vendedor(a),2013-12-02,ATIVO,SAN,574403,30,SIM,NAO
561,21010,LUCIANA,SOARES,ASSESSOR DE LOJA,2013-12-10,ATIVO,SAN,574402,30,SIM,NAO
569,21199,JUNIOR,DOS REIS,Vendedor(a),2014-02-10,ATIVO,SAN,574403,30,SIM,NAO
572,21242,ERALDO,DA COSTA,Ger de Vendas I,2014-02-14,ATIVO,SAN,574401,30,SIM,NAO
802,24071,RENATO,FERREIRA,Vendedor(a),2016-07-07,ATIVO,SAN,574403,30,SIM,NAO
822,24193,MANUEL,DOS REIS ANDRADE DOS SANTOS,Enc Depósito,2016-09-02,ATIVO,SAN,574406,30,SIM,NAO
849,24386,RONEY,BOER,Vendedor(a),2016-11-07,Férias,SAN,574403,30,SIM,NAO
867,24488,GERSILEIDE,MARICATO,Vendedor(a),2016-12-08,ATIVO,SAN,574403,30,SIM,NAO
868,24499,MARIA,DIAS,Ger de Vendas I,2016-12-12,ATIVO,SAN,574401,30,SIM,NAO
921,24837,EDUARDO,TRINDADE,Oficial Manutenção Eletricista,2017-04-03,ATIVO,SAN,574402,30,SIM,NAO
922,24839,EDILEUZA,DE SOUZA,Vendedor(a),2017-04-04,ATIVO,SAN,574403,30,SIM,NAO
923,24840,ALESSANDRO,DE BRITO,Vendedor(a),2017-04-04,ATIVO,SAN,574403,30,SIM,NAO
1064,25683,LORRAINA,COSTA,Vendedor(a),2018-03-13,ATIVO,SAN,574403,30,SIM,NAO
1070,25718,TAYNA,LIMA,Vendedor(a),2018-03-20,Férias,SAN,574403,30,SIM,NAO
1203,26390,CARLOS,DA CRUZ FILHO,Vendedor(a),2018-10-11,ATIVO,SAN,574403,30,SIM,NAO
1207,26398,ELIANE,CRISTINO,Ass Serviços ao Cliente,2018-10-11,ATIVO,SAN,574402,30,SIM,NAO
1229,26466,FABIO,DE LIMA,Ger Geral II,2018-11-01,ATIVO,SAN,574401,30,SIM,NAO
1238,26495,MARILIA,NAVARRO,Vendedor(a),2018-11-12,ATIVO,SAN,574403,30,SIM,NAO
1239,26494,FERNANDA,CAVALCANTE,Vendedor(a),2018-11-12,ATIVO,SAN,574403,30,SIM,NAO
1287,26675,ANDRE,SILVA,Assessor de Operações I,2019-01-07,ATIVO,SAN,574403,30,SIM,NAO
1288,26679,SIMONE,DE LIMA,Vendedor(a),2019-01-14,ATIVO,SAN,574403,30,SIM,NAO
1313,26774,YASMIN,CAVALCANTE,ASSESSOR DE LOJA,2019-02-18,Licença,SAN,574402,30,SIM,NAO
1334,26873,ANDREIA,SILVA,Ass Serviços ao Cliente,2019-04-01,ATIVO,SAN,574402,30,SIM,NAO
1341,26898,BEATRIZ,FERRAZ,Ass de Expedição,2019-04-15,ATIVO,SAN,574406,30,SIM,NAO
1413,27207,FABIANA,DA SILVA,Vendedor(a),2019-08-05,ATIVO,SAN,574403,30,SIM,NAO
1500,27539,ABDIAS,PEREIRA JUNIOR,ASSESSOR DE LOJA,2019-11-11,ATIVO,SAN,574402,30,SIM,NAO
1509,27562,FABIO,DE ARAUJO,Vendedor(a),2019-11-18,ATIVO,SAN,574403,30,SIM,NAO
1520,27598,VICTOR,GONCALVES,ASSESSOR DE LOJA,2019-12-02,ATIVO,SAN,574402,30,SIM,NAO
1522,27601,FELIPE,SILVA,Ass Serviços ao Cliente,2019-12-02,ATIVO,SAN,809363,30,SIM,NAO
1565,27739,BRUNA,BAPTISTA,Ass de Expedição,2020-01-13,ATIVO,SAN,574406,30,SIM,NAO
1716,28272,AMANDA,DE LIMA,DESIGNER PROJETISTA,2020-10-05,ATIVO,SAN,574403,30,SIM,NAO
1728,28296,CAIO,DOS SANTOS,ASSESSOR DE LOJA,2020-10-13,ATIVO,SAN,574403,30,SIM,NAO
1736,28320,MARCELO,DE SOUZA,ASSESSOR DE LOJA,2020-10-19,ATIVO,SAN,574402,30,SIM,NAO
1759,28388,RODRIGO,MUNIZ,ASSESSOR DE LOJA,2020-11-03,ATIVO,SAN,574403,30,SIM,NAO
1764,28411,TAMARA,FERREIRA,Ass Serviços ao Cliente,2020-11-09,ATIVO,SAN,574402,30,SIM,NAO
1771,28421,CRISTINA,DE ABREU,ASSESSOR DE LOJA,2020-11-09,Atestado,SAN,574403,30,SIM,NAO
1829,28548,ALINE,FERREIRA,ASSESSOR DE LOJA,2020-12-07,ATIVO,SAN,574403,30,SIM,NAO
1916,28723,LUCAS,DA SILVA,Assessor de Operações I,2021-01-11,ATIVO,SAN,574406,30,SIM,NAO
1924,28732,ANDRE,DA SILVA,ASSESSOR DE LOJA,2021-01-18,ATIVO,SAN,574403,30,SIM,NAO
1933,28746,MATHEUS,SILVA,ASSESSOR DE LOJA,2021-01-18,ATIVO,SAN,574403,30,SIM,NAO
1958,28821,PASCOAL,PERES,Ger Operacional I,2021-02-08,ATIVO,SAN,574401,30,SIM,NAO
2193,29374,CLAUDIO,SAAD,Consultor de Vendas Externas,2021-09-20,ATIVO,SAN,574401,30,SIM,NAO

In [115]:
# INCLUINDO DIAS AFASTADOS TOTAIS DA MATRÍCULA
tina_afastados=pd.merge(
    tina,
    dias_afastados_por_matricula[
        ['MATRICULA','dias_afastados_totais']
        ],
        how='left',
        on=['MATRICULA']
        )

In [116]:
# PREENCHENDO COM ZERO ATIVOS SEM AFASTAMENTOS
tina_afastados['dias_afastados_totais'].fillna(0, inplace=True)

In [117]:
tina_afastados[tina_afastados['MATRICULA']==25333]

,MATRICULA,NOME,SOBRENOME,CARGO,DATA_ADMISSAO,STATUS,LOJA,Centro de Resultado - Código,DIAS_ADMITIDOS,MAIS_DE15DIAS_ADMITIDOS,LOJA_ELEGIVEL,dias_afastados_totais
724,25333,ALDERICO,QUEIROZ,Repositor(a),2017-11-09,Auxilio,PMG,234406,30,SIM,NAO,30.0

In [118]:
# CALCULANDO DIAS ATIVOS NO PERÍODO DE APURAÇÃO CONSIDERANDO A DATA DE ADMISSÃO
tina_afastados['DIAS_ATIVOS']=tina_afastados['DIAS_ADMITIDOS']-tina_afastados['dias_afastados_totais']

In [119]:
tina_afastados[tina_afastados['MATRICULA']==6068]

,MATRICULA,NOME,SOBRENOME,CARGO,DATA_ADMISSAO,STATUS,LOJA,Centro de Resultado - Código,DIAS_ADMITIDOS,MAIS_DE15DIAS_ADMITIDOS,LOJA_ELEGIVEL,dias_afastados_totais,DIAS_ATIVOS
39,6068,LINDOVAL,DA SILVA,Repositor(a),2003-02-05,Suspensão,PMG,234402,30,SIM,NAO,30.0,0.0

In [120]:
tina_afastados['MAIS_DE15DIAS_ATIVOS']=np.where(
    tina_afastados['DIAS_ATIVOS']>=MEIO_MES, 'SIM','NAO'
    )

In [121]:
tina_afastados[tina_afastados['LOJA']=='SAN']

,MATRICULA,NOME,SOBRENOME,CARGO,DATA_ADMISSAO,STATUS,LOJA,Centro de Resultado - Código,DIAS_ADMITIDOS,MAIS_DE15DIAS_ADMITIDOS,LOJA_ELEGIVEL,dias_afastados_totais,DIAS_ATIVOS,MAIS_DE15DIAS_ATIVOS
12,2579,MARLENE,DE SANTANA,Enc de Caixa,1999-06-07,ATIVO,SAN,574402,30,SIM,NAO,0.0,30.0,SIM
55,6591,ROSANA,FERNANDES,Vendedor(a),2003-08-04,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
57,6790,GERALDO,DA COSTA,Vendedor(a),2003-11-03,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
116,9716,ANDERSON,NASCIMENTO,Vendedor(a),2006-12-14,Auxilio,SAN,574403,30,SIM,NAO,30.0,0.0,NAO
126,10361,ENILSON,CORREIA,Ger de Produto II,2007-05-02,Auxilio,SAN,574401,30,SIM,NAO,30.0,0.0,NAO
332,18882,ADELSON,DE SOUZA,Vendedor(a),2012-07-02,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
385,20765,LUIZ,GOIS,Operador Empilhadeira,2013-10-15,ATIVO,SAN,574406,30,SIM,NAO,0.0,30.0,SIM
388,20825,JOSY,DOS SANTOS,Lider de Caixa,2013-11-01,Auxilio,SAN,574402,30,SIM,NAO,30.0,0.0,NAO
392,20948,LILIAN,LOPES,Vendedor(a),2013-12-02,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
397,21010,LUCIANA,SOARES,ASSESSOR DE LOJA,2013-12-10,ATIVO,SAN,574402,30,SIM,NAO,8.0,22.0,SIM
402,21199,JUNIOR,DOS REIS,Vendedor(a),2014-02-10,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
403,21242,ERALDO,DA COSTA,Ger de Vendas I,2014-02-14,ATIVO,SAN,574401,30,SIM,NAO,0.0,30.0,SIM
564,24071,RENATO,FERREIRA,Vendedor(a),2016-07-07,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
583,24193,MANUEL,DOS REIS ANDRADE DOS SANTOS,Enc Depósito,2016-09-02,ATIVO,SAN,574406,30,SIM,NAO,0.0,30.0,SIM
608,24386,RONEY,BOER,Vendedor(a),2016-11-07,Férias,SAN,574403,30,SIM,NAO,5.0,25.0,SIM
624,24488,GERSILEIDE,MARICATO,Vendedor(a),2016-12-08,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
625,24499,MARIA,DIAS,Ger de Vendas I,2016-12-12,ATIVO,SAN,574401,30,SIM,NAO,16.0,14.0,NAO
659,24837,EDUARDO,TRINDADE,Oficial Manutenção Eletricista,2017-04-03,ATIVO,SAN,574402,30,SIM,NAO,0.0,30.0,SIM
660,24839,EDILEUZA,DE SOUZA,Vendedor(a),2017-04-04,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
661,24840,ALESSANDRO,DE BRITO,Vendedor(a),2017-04-04,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
764,25683,LORRAINA,COSTA,Vendedor(a),2018-03-13,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
769,25718,TAYNA,LIMA,Vendedor(a),2018-03-20,Férias,SAN,574403,30,SIM,NAO,3.0,27.0,SIM
856,26390,CARLOS,DA CRUZ FILHO,Vendedor(a),2018-10-11,ATIVO,SAN,574403,30,SIM,NAO,26.0,4.0,NAO
858,26398,ELIANE,CRISTINO,Ass Serviços ao Cliente,2018-10-11,ATIVO,SAN,574402,30,SIM,NAO,0.0,30.0,SIM
872,26466,FABIO,DE LIMA,Ger Geral II,2018-11-01,ATIVO,SAN,574401,30,SIM,NAO,0.0,30.0,SIM
874,26495,MARILIA,NAVARRO,Vendedor(a),2018-11-12,ATIVO,SAN,574403,30,SIM,NAO,26.0,4.0,NAO
875,26494,FERNANDA,CAVALCANTE,Vendedor(a),2018-11-12,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
912,26675,ANDRE,SILVA,Assessor de Operações I,2019-01-07,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
913,26679,SIMONE,DE LIMA,Vendedor(a),2019-01-14,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
936,26774,YASMIN,CAVALCANTE,ASSESSOR DE LOJA,2019-02-18,Licença,SAN,574402,30,SIM,NAO,30.0,0.0,NAO
950,26873,ANDREIA,SILVA,Ass Serviços ao Cliente,2019-04-01,ATIVO,SAN,574402,30,SIM,NAO,0.0,30.0,SIM
954,26898,BEATRIZ,FERRAZ,Ass de Expedição,2019-04-15,ATIVO,SAN,574406,30,SIM,NAO,0.0,30.0,SIM
993,27207,FABIANA,DA SILVA,Vendedor(a),2019-08-05,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
1064,27539,ABDIAS,PEREIRA JUNIOR,ASSESSOR DE LOJA,2019-11-11,ATIVO,SAN,574402,30,SIM,NAO,12.0,18.0,SIM
1072,27562,FABIO,DE ARAUJO,Vendedor(a),2019-11-18,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
1083,27598,VICTOR,GONCALVES,ASSESSOR DE LOJA,2019-12-02,ATIVO,SAN,574402,30,SIM,NAO,0.0,30.0,SIM
1085,27601,FELIPE,SILVA,Ass Serviços ao Cliente,2019-12-02,ATIVO,SAN,809363,30,SIM,NAO,0.0,30.0,SIM
1122,27739,BRUNA,BAPTISTA,Ass de Expedição,2020-01-13,ATIVO,SAN,574406,30,SIM,NAO,0.0,30.0,SIM
1228,28272,AMANDA,DE LIMA,DESIGNER PROJETISTA,2020-10-05,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
1239,28296,CAIO,DOS SANTOS,ASSESSOR DE LOJA,2020-10-13,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
1245,28320,MARCELO,DE SOUZA,ASSESSOR DE LOJA,2020-10-19,ATIVO,SAN,574402,30,SIM,NAO,0.0,30.0,SIM
1262,28388,RODRIGO,MUNIZ,ASSESSOR DE LOJA,2020-11-03,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
1265,28411,TAMARA,FERREIRA,Ass Serviços ao Cliente,2020-11-09,ATIVO,SAN,574402,30,SIM,NAO,5.0,25.0,SIM
1271,28421,CRISTINA,DE ABREU,ASSESSOR DE LOJA,2020-11-09,Atestado,SAN,574403,30,SIM,NAO,8.0,22.0,SIM
1316,28548,ALINE,FERREIRA,ASSESSOR DE LOJA,2020-12-07,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
1379,28723,LUCAS,DA SILVA,Assessor de Operações I,2021-01-11,ATIVO,SAN,574406,30,SIM,NAO,3.0,27.0,SIM
1381,28732,ANDRE,DA SILVA,ASSESSOR DE LOJA,2021-01-18,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
1384,28746,MATHEUS,SILVA,ASSESSOR DE LOJA,2021-01-18,ATIVO,SAN,574403,30,SIM,NAO,0.0,30.0,SIM
1398,28821,PASCOAL,PERES,Ger Operacional I,2021-02-08,ATIVO,SAN,574401,30,SIM,NAO,0.0,30.0,SIM
1557,29374,CLAUDIO,SAAD,Consultor de Vendas Externas,2021-09-20,ATIVO,SAN,574401,30,SIM,NAO,0.0,30.0,SIM

In [122]:
# PARA RENOMEAR PARÂMETROS DE ALVO E NPS E INCLUIR NA PLANILHA DE CHECAGEM
RENOMEA={
    'sigla_loja':'LOJA',
    'alvo':'ALVO_ALCANCADO',
    'nps':'NPS'
    }

In [123]:
loja_nps_venda_alvo[loja_nps_venda_alvo['cod_loja']<510000]

,cod_loja,sigla_loja,Venda_Total,nps,id_mes,target_sales_store_1,target_sales_store_2,alvo,NPS_alcancado
0,19,IMI,7651333.72,64.6,202204.0,8026309.0,8302751.0,NAO,NAO
1,25,ZNO,6025262.19,63.3,202204.0,6496375.0,6800432.0,NAO,NAO
2,28,SOR,3281824.60,69.2,202204.0,3843981.0,4039012.0,NAO,SIM
3,43,TAT,3116576.28,66.7,202204.0,3021009.0,3188370.0,ALVO1,SIM
4,8,PGD,2457010.48,56.9,202204.0,3025118.0,3200657.0,NAO,NAO
5,12,JDI,5629601.58,68.6,202204.0,5201755.0,5417401.0,ALVO2,SIM
6,27,OSA,1615072.13,70.6,202204.0,2024388.0,2169889.0,NAO,SIM
7,31,BEL,1797914.63,72.5,202204.0,2513037.0,2695489.0,NAO,SIM
8,38,DPE,1804328.79,83.1,202204.0,2348111.0,2479512.0,NAO,SIM
9,40,TAM,3889825.30,80.0,202204.0,4403925.0,4614318.0,NAO,SIM
10,54,MGA,1621650.37,72.2,202204.0,2437710.0,2612566.0,NAO,SIM
11,57,ARP,2089312.16,69.4,202204.0,2257801.0,2418465.0,NAO,SIM
12,70,WHL,1286499.53,48.9,202204.0,1548968.0,1651055.0,NAO,NAO
13,71,RDV,3447183.35,67.6,202204.0,3627299.0,3868503.0,NAO,SIM
14,73,TBT,1792231.17,74.5,202204.0,2126228.0,2274356.0,NAO,SIM
15,74,RPT,1946969.77,76.9,202204.0,2728981.0,2893058.0,NAO,SIM
16,75,AMZ,1070910.30,61.3,202204.0,1599580.0,1698420.0,NAO,NAO
17,1,ANH,3290470.81,69.7,202204.0,4222729.0,4417709.0,NAO,SIM
18,3,MGN,19755502.86,55.4,202204.0,19556614.0,20365671.0,ALVO1,NAO
19,9,SA1,2883713.64,58.8,202204.0,2982561.0,3141049.0,NAO,NAO
20,22,TAB,1935086.80,70.6,202204.0,2277617.0,2415186.0,NAO,SIM
21,23,PMG,2839836.89,53.1,202204.0,2933834.0,3213696.0,NAO,NAO
22,24,ARI,8077677.11,55.7,202204.0,8462883.0,8794235.0,NAO,NAO
23,26,SJC,4647668.70,67.7,202204.0,5040452.0,5269598.0,NAO,SIM
24,29,PAR,1728748.41,58.5,202204.0,1768299.0,1951614.0,NAO,NAO
25,30,MOR,10236851.21,61.0,202204.0,10474420.0,10843131.0,NAO,NAO
26,32,GRU,3067211.96,57.9,202204.0,3290751.0,3501658.0,NAO,NAO
27,34,PAM,2205361.70,62.5,202204.0,2593292.0,2772994.0,NAO,NAO
28,36,CTG,1830317.73,72.1,202204.0,3011064.0,3203174.0,NAO,SIM
29,37,PIR,2140641.81,71.1,202204.0,2538288.0,2689959.0,NAO,SIM
30,39,UBE,1500313.55,87.0,202204.0,1892494.0,2039986.0,NAO,SIM
31,48,BRG,1595695.62,67.4,202204.0,1507592.0,1625143.0,ALVO1,SIM
32,51,TIR,2902479.81,69.8,202204.0,3809933.0,3991701.0,NAO,SIM
33,52,CAT,1338749.13,63.6,202204.0,1702626.0,1820097.0,NAO,NAO
34,55,PRU,2152571.37,78.7,202204.0,2927500.0,3139764.0,NAO,SIM
35,56,CLI,2696604.22,57.4,202204.0,3042992.0,3206973.0,NAO,NAO
36,64,SAN,3858814.93,78.0,202204.0,5139625.0,5351774.0,NAO,SIM
37,66,RAP,1949031.72,71.1,202204.0,2566428.0,2726896.0,NAO,SIM
38,72,SCA,1792661.11,81.8,202204.0,1753628.0,1873650.0,ALVO1,SIM

In [124]:
telha_nps_venda_alvo=loja_nps_venda_alvo[loja_nps_venda_alvo['cod_loja']<510000]

In [125]:
# PREPARANDO PLANILHA DE CHECAGEM
tina_tudo=pd.merge(
    tina_afastados,
    telha_nps_venda_alvo[['sigla_loja', 'alvo','nps']].rename(columns=RENOMEA),
    how='left',
    on='LOJA'
    )

In [126]:
tina_copia=tina_tudo

In [127]:
# CARREGANDO TODOS OS CARGOS CONTEMPLADOS PELA PREMIAÇÃO COLETIVA
cargos=pd.read_csv(F_CARGOS, sep=';')

In [128]:
# ATRIBUINDO O GRUPO DE PREMIAÇÃO PARA CADA CARGO
tina_tudo=pd.merge(
    tina_tudo, 
    cargos.rename(columns={'Cargo':'CARGO'}),
    how='left',
    on='CARGO'
    )

In [129]:
tina_tudo['Grupo'].fillna('NAO TINA', inplace=True)

In [130]:
# Função para atribuir valor da premiação dependendo do grupo de cargo
def premiacao_alvo(grupo,alvo):
    global PREMIOS
    alvo1 = dict(zip(PREMIOS['Grupo'], PREMIOS['ALVO1']))
    alvo2 = dict(zip(PREMIOS['Grupo'], PREMIOS['ALVO2']))
    if alvo == 'ALVO1':
        valor=alvo1[grupo]
    elif alvo == 'ALVO2':
        valor=alvo2[grupo]
    elif alvo == 'NAO':
        valor = 0.0
    else: valor=0.0
    return valor

In [131]:
# Atribuindo valor da premiação dependendo do grupo de cargo
tina_tudo['PREMIACAO']=tina_tudo.apply(
    lambda x: premiacao_alvo(
        x['Grupo'],x['ALVO_ALCANCADO'],
    ), axis=1)

In [132]:
tina_tudo['FALTAS']=np.where(tina_tudo['MATRICULA'].isin(faltas['MATRICULA']),'SIM','NAO')

In [133]:
tina_tudo['APTO_PREMIACAO']=np.where(
    (tina_tudo['LOJA_ELEGIVEL']=='SIM') &
        (tina_tudo['MAIS_DE15DIAS_ATIVOS']=='SIM') &
        (tina_tudo['FALTAS']=='NAO') &
        (tina_tudo['Grupo']!='NAO TINA') &
        (tina_tudo['PREMIACAO']>0),
        'SIM','NAO'
    )

In [134]:
#Salvando verba
# Entradas: v verba, n nome_verba, x numero_verba, f f_nome
def salva_verba(verba,num_verba,arq_nome):
#    v.rename(columns={ v.columns[0]: 'MATRICULA'}, inplace=True)
    verba.rename(columns={ verba.columns[1]: "VALOR" }, inplace=True)
    verba['ZERO'] = 0
    verba['VERBA'] = num_verba
    verba=verba[['MATRICULA', 'ZERO', 'VERBA','VALOR']]
    verba = verba[verba['VALOR'] > 0]
    # Saving as a excel file for RH
    writer = pd.ExcelWriter(arq_nome, engine='xlsxwriter')  # #
    verba.to_excel(writer, sheet_name="VERBA "+str(num_verba), index=False)
    writer.save()

In [135]:
# Salva verba apuração coletiva
salva_verba(
    tina_tudo[['MATRICULA', 'PREMIACAO']][
        (tina_tudo['LOJA_ELEGIVEL']=='SIM') &
        (tina_tudo['MAIS_DE15DIAS_ATIVOS']=='SIM') &
        (tina_tudo['FALTAS']=='NAO')
    ].copy(),4117,FILE_SAI)

In [136]:
# Salva verba apuração coletiva
salva_verba(
    tina_tudo[['MATRICULA', 'PREMIACAO']][
        (tina_tudo['LOJA_ELEGIVEL']=='SIM') &
        (tina_tudo['MAIS_DE15DIAS_ATIVOS']=='SIM')
    ].copy(),4117,FILE_SAI_SEM)

In [137]:
# SALVA PLANILHA DE CHECAGEM
tina_tudo.to_excel(FILE_CHECAGEM, index=False)